/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
Aaca ava a ir los espetaculos
 */
package coronatickets.espetaculos;
import Clases.Espectaculo;
import coronatickets.espetaculos.create;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import logica.Fabrica;
import logica.interfaz.IControladorEspetaculo;
import coronatickets.espetaculos.consultaEspetaculo;
/**
 *
 * @author Nico
 */
public class admin extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    private IControladorEspetaculo ICE;
    public admin() {
        this.ICE = Fabrica.getInstance().getIControladorEspectaculo();
        initComponents();
        cargarTabla();
    }
    
    
    public void cargarTabla()
    {
        DefaultTableModel table = new DefaultTableModel();
        ArrayList<Espectaculo> datos;
        String[] filas = new String[5];
        table.addColumn("Nombre");
        table.addColumn("Artista");
        table.addColumn("Plataforma");
        table.addColumn("URL");
        table.addColumn("Costo");
        datos = ICE.tblEspectaculo();
        for(int i = 0; i<datos.size(); i++)
        {
            filas[0] = datos.get(i).getNombre().toString();
            filas[1] = datos.get(i).getDescripcion().toString();
            filas[2] = datos.get(i).getPLataforma();
            filas[3] = datos.get(i).getURL().toString();
            filas[4] = String.valueOf(datos.get(i).getCosto());
            table.addRow(filas);
        }
        tablaEspetaculos.setModel(table);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEspetaculos = new javax.swing.JTable();
        btnCrearEspetaculo = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Espetaculos");

        tablaEspetaculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaEspetaculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEspetaculosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaEspetaculos);

        btnCrearEspetaculo.setText("Crear");
        btnCrearEspetaculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearEspetaculoActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(172, 172, 172)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCrearEspetaculo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCrearEspetaculo)
                        .addComponent(btnBuscar)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearEspetaculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearEspetaculoActionPerformed
        create fmCreate = new create();
        fmCreate.show(true);
    }//GEN-LAST:event_btnCrearEspetaculoActionPerformed

    private void tablaEspetaculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEspetaculosMouseClicked
      int fila = tablaEspetaculos.getSelectedRow();
      String nombre = (String) tablaEspetaculos.getValueAt(fila,0);//selecciono de la fila seleccionada la primera
      
      datosEspectaculo(nombre);
    }//GEN-LAST:event_tablaEspetaculosMouseClicked

    
    public void datosEspectaculo(String nombre)
    {
        Espectaculo esp = ICE.obtenerDato(nombre);
        /*this.nombre.setText(esp.getNombre());
        this.artista.setText(esp.getArtistaOrganizador());
        this.plataforma.setText(esp.getPLataforma());
        this.descripcion.setText(esp.getDescripcion());
        this.max.setText(String.valueOf(esp.getCapacidadMaxima()));
        this.min.setText(String.valueOf(esp.getCapacidadMinima()));
        this.url.setText(esp.getURL());
        this.costo.setText(String.valueOf(esp.getCosto()));
        this.fecha.setText(esp.getFechaCreado().toString());*/
        
    }
    
    
    
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        consultaEspetaculo fmCreate = new consultaEspetaculo();
        fmCreate.show(true);
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCrearEspetaculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaEspetaculos;
    // End of variables declaration//GEN-END:variables
}
