/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coronatickets.espetaculos;
<<<<<<< HEAD
import Clases.Artista;
import logica.Fabrica;
import logica.interfaz.IControladorEspetaculo;;
import java.util.ArrayList;
import Clases.Plataformas;
import javax.swing.*;
import logica.interfaz.IControladorUsuario;
=======

import Clases.Artista;
import Clases.Categoria;
import logica.Fabrica;
import logica.interfaz.IControladorEspetaculo;
import java.util.List;
import javax.swing.*;
import java.util.ArrayList;
import Clases.Plataformas;
import java.io.File;
import logica.interfaz.IControladorUsuario;

>>>>>>> 2c68efd283358ad6834c5a1e2c6affc39b92eeb7
/**
 *
 * @author Nico
 */
public class create extends javax.swing.JFrame {

    private IControladorEspetaculo ICE;
    private IControladorUsuario ICU;
<<<<<<< HEAD
=======

>>>>>>> 2c68efd283358ad6834c5a1e2c6affc39b92eeb7
    /**
     * Creates new form create
     */
    public create() {
        this.ICE = Fabrica.getInstance().getIControladorEspectaculo();
        this.ICU = Fabrica.getInstance().getIControladorUsuario();
        initComponents();
        cargarComboBox();
    }
<<<<<<< HEAD
    
    public void cargarComboBox(){
        ArrayList<Plataformas> datos;
        ArrayList<Artista> datosArt;
        sctPlataformas.addItem("Seleccione una opcion"); 
        sctArtista.addItem("Seleccione una opcion");
        datos = ICE.tblPlataforma();
        datosArt = ICU.tablaArtistas();
        for(int i = 0; i<datos.size(); i++)
        {
            sctPlataformas.addItem(datos.get(i).getNombre());
        }
        
        for(int i = 0; i<datosArt.size(); i++)
        {
            sctArtista.addItem(datosArt.get(i).getNickname());
        }
    }

    
    
=======

    public void cargarComboBox() {
        ArrayList<Plataformas> datos;
        ArrayList<Artista> datosArt;
        ArrayList<Categoria> categorias;
        sctPlataformas.addItem("Seleccione una opcion");
        sctArtista.addItem("Seleccione una opcion");
        datos = ICE.tblPlataforma();
        datosArt = ICU.tablaArtistas();
        categorias = ICE.tblCategoria();

        for (int i = 0; i < datos.size(); i++) {
            sctPlataformas.addItem(datos.get(i).getNombre());
        }

        for (int i = 0; i < datosArt.size(); i++) {
            sctArtista.addItem(datosArt.get(i).getNickname());
        }

        DefaultListModel list = new DefaultListModel();
        for (int i = 0; i < categorias.size(); i++) {
            list.addElement(categorias.get(i).getNombre());
        }
        lstCategorias.setModel(list);
    }

>>>>>>> 2c68efd283358ad6834c5a1e2c6affc39b92eeb7
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

<<<<<<< HEAD
=======
        jLabel1 = new javax.swing.JLabel();
>>>>>>> 2c68efd283358ad6834c5a1e2c6affc39b92eeb7
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        sctPlataformas = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        sctArtista = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        txtDuracion = new javax.swing.JSpinner();
        txtEspectadorMin = new javax.swing.JSpinner();
        txtEspectadorMax = new javax.swing.JSpinner();
        txtUrl = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCosto = new javax.swing.JSpinner();
<<<<<<< HEAD

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear espectaculo");
=======
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstCategorias = new javax.swing.JList<>();
        lblImagen = new javax.swing.JLabel();
        btnImagen4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Crear Espetaculo");
>>>>>>> 2c68efd283358ad6834c5a1e2c6affc39b92eeb7

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Plataforma:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Organizador:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Nombre:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Descripcion:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Duracion:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Espectadores minimo:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("URL:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Espectadores maximo:");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        txtDescripcion.setPreferredSize(new java.awt.Dimension(110, 94));
        jScrollPane1.setViewportView(txtDescripcion);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Costo:");

<<<<<<< HEAD
=======
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Categorias:");

        jScrollPane2.setViewportView(lstCategorias);

        btnImagen4.setText("Agregar imagen");
        btnImagen4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImagen4MouseClicked(evt);
            }
        });

>>>>>>> 2c68efd283358ad6834c5a1e2c6affc39b92eeb7
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< HEAD
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(34, 34, 34)
                                .addComponent(sctPlataformas, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel4)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sctArtista, 0, 139, Short.MAX_VALUE)
                                    .addComponent(txtNombre))))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAceptar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addGap(107, 107, 107))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel8)))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEspectadorMin)
                            .addComponent(txtEspectadorMax, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21))
=======
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnImagen4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(34, 34, 34)
                                        .addComponent(sctPlataformas, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel4)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(sctArtista, 0, 139, Short.MAX_VALUE)
                                            .addComponent(txtNombre))))
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAceptar)
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)))
                                .addGap(31, 31, 31))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel8)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEspectadorMax, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEspectadorMin, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(31, 31, 31))))
                    .addComponent(lblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
>>>>>>> 2c68efd283358ad6834c5a1e2c6affc39b92eeb7
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
<<<<<<< HEAD
                .addContainerGap(26, Short.MAX_VALUE)
=======
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
>>>>>>> 2c68efd283358ad6834c5a1e2c6affc39b92eeb7
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sctPlataformas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sctArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
<<<<<<< HEAD
                        .addComponent(jLabel7)
                        .addGap(118, 118, 118))
=======
                        .addComponent(jLabel7))
>>>>>>> 2c68efd283358ad6834c5a1e2c6affc39b92eeb7
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtEspectadorMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtEspectadorMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
<<<<<<< HEAD
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addGap(18, 18, 18))
=======
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnImagen4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnAceptar))
                    .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
>>>>>>> 2c68efd283358ad6834c5a1e2c6affc39b92eeb7
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String plataforma = (String) sctPlataformas.getSelectedItem();
        String artista = (String) sctArtista.getSelectedItem();
        String nombre = txtNombre.getText();
        String descripcion = txtDescripcion.getText();
        int duracion = (int) txtDuracion.getValue();
        int maximo = (int) txtEspectadorMax.getValue();
        int minimo = (int) txtEspectadorMin.getValue();
        String url = txtUrl.getText();
        boolean continuar = true;
        int costo = (int) txtCosto.getValue();
<<<<<<< HEAD
        if(plataforma.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "La plataforma es obligaotoria.");
            continuar = false;
        }
        if(artista.isEmpty() && continuar)
        {
            JOptionPane.showMessageDialog(this, "El artista organizador es obligatorio.");
            continuar = false;
        }
        if(nombre.isEmpty() && continuar)
        {
            JOptionPane.showMessageDialog(this, "El nombre es obligatorio.");
            continuar = false;
        }
        
        if(duracion <= 0 && continuar)
        {
            JOptionPane.showMessageDialog(this, "La duracion no pueder 0 ni inferior.");
            continuar = false;
        }
        
        if(maximo <= 0 && continuar)
        {
            JOptionPane.showMessageDialog(this, "El maximo espectador no puede ser 0 o inferior.");
            continuar = false;
        }
        
        if(minimo <=0 && continuar)
        {
            JOptionPane.showMessageDialog(this, "El minimo de espectador no puede ser 0 e inferior.");
            continuar = false;
        }
        
        if(maximo <= minimo && continuar)
        {
            JOptionPane.showMessageDialog(this, "El maximo no puede ser menor o igual al minimo.");
            continuar = false;
        }
        
        if(minimo >= maximo && continuar)
        {
            JOptionPane.showMessageDialog(this, "El minimo no puede ser mayor al maximo de espectadores.");
            continuar = false;
        }
        
        if(url.isEmpty() && continuar)
        {
            JOptionPane.showMessageDialog(this, "La url es obligatoria.");
            continuar = false;
        }
        
        if(costo < 0 && continuar)
        {
            JOptionPane.showMessageDialog(this, "El costo no puede ser menor que 0.");
            continuar = false;
        }
        
        if(continuar)
        {
            String creo = ICE.crearEspetaculo(plataforma, artista ,nombre, duracion, maximo, minimo, url, costo, descripcion);
            if(creo == "S")//Todo OK
            {
                JOptionPane.showMessageDialog(this, "Creado con exito.");
                dispose();
            }else{
                JOptionPane.showMessageDialog(this, "Erro a la hora de crear la plataforma  .");
            }
        }
        
    }//GEN-LAST:event_btnAceptarActionPerformed

=======

        if (sctPlataformas.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "La plataforma es obligaotoria.");
            continuar = false;
        }
        if (sctArtista.getSelectedIndex() == 0 && continuar) {
            JOptionPane.showMessageDialog(this, "El artista organizador es obligatorio.");
            continuar = false;
        }
        if (nombre.isEmpty() && continuar) {
            JOptionPane.showMessageDialog(this, "El nombre es obligatorio.");
            continuar = false;
        }

        if (duracion <= 0 && continuar) {
            JOptionPane.showMessageDialog(this, "La duracion no pueder 0 ni inferior.");
            continuar = false;
        }

        if (maximo <= 0 && continuar) {
            JOptionPane.showMessageDialog(this, "El maximo espectador no puede ser 0 o inferior.");
            continuar = false;
        }

        if (minimo <= 0 && continuar) {
            JOptionPane.showMessageDialog(this, "El minimo de espectador no puede ser 0 e inferior.");
            continuar = false;
        }

        if (maximo <= minimo && continuar) {
            JOptionPane.showMessageDialog(this, "El maximo no puede ser menor o igual al minimo.");
            continuar = false;
        }

        if (minimo >= maximo && continuar) {
            JOptionPane.showMessageDialog(this, "El minimo no puede ser mayor al maximo de espectadores.");
            continuar = false;
        }

        if (url.isEmpty() && continuar) {
            JOptionPane.showMessageDialog(this, "La url es obligatoria.");
            continuar = false;
        }

        if (costo < 0 && continuar) {
            JOptionPane.showMessageDialog(this, "El costo no puede ser menor que 0.");
            continuar = false;
        }

        if (lstCategorias.getSelectedIndex() == -1 && continuar) {
            JOptionPane.showMessageDialog(null, "Seleccione categorias para la funcion");
            continuar = false;
        }

        if (continuar == true) {

            List categorias = lstCategorias.getSelectedValuesList();
            
             File imagen = new File(this.lblImagen.getText());

            String creo = ICE.crearEspetaculo(plataforma, artista, nombre, descripcion, duracion, maximo, minimo, url, costo, categorias, imagen);
            if (creo == "S")//Todo OK
            {
                JOptionPane.showMessageDialog(this, "Creado con exito.");
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Erro a la hora de crear la plataforma  .");
            }
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnImagen4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImagen4MouseClicked
        JFileChooser imagen = new JFileChooser();
        imagen.showOpenDialog(this);

        File archivo = imagen.getSelectedFile();

        if (archivo != null) {
            String origen = archivo.getPath();

            this.lblImagen.setText(origen);
        }
    }//GEN-LAST:event_btnImagen4MouseClicked

>>>>>>> 2c68efd283358ad6834c5a1e2c6affc39b92eeb7
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new create().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
<<<<<<< HEAD
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
=======
    private javax.swing.JButton btnImagen;
    private javax.swing.JButton btnImagen1;
    private javax.swing.JButton btnImagen2;
    private javax.swing.JButton btnImagen3;
    private javax.swing.JButton btnImagen4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
>>>>>>> 2c68efd283358ad6834c5a1e2c6affc39b92eeb7
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
<<<<<<< HEAD
=======
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JList<String> lstCategorias;
>>>>>>> 2c68efd283358ad6834c5a1e2c6affc39b92eeb7
    private javax.swing.JComboBox<String> sctArtista;
    private javax.swing.JComboBox<String> sctPlataformas;
    private javax.swing.JSpinner txtCosto;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JSpinner txtDuracion;
    private javax.swing.JSpinner txtEspectadorMax;
    private javax.swing.JSpinner txtEspectadorMin;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUrl;
    // End of variables declaration//GEN-END:variables
}
