    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coronatickets.espetaculos;
import Clases.Espectaculo;
import javax.swing.table.DefaultTableModel;
import logica.Fabrica;
import logica.interfaz.*;
import Interface.IControladorFuncion;
import coronatickets.funciones.consultaFuncion;
import coronatickets.paquetes.datosPaquetes;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Nico
 */
public class espectaculosIngresados extends javax.swing.JFrame {

    private IControladorEspetaculo ICE;
    private IControladorPaquetes ICP;
    private IControladorFuncion ICF;
    /**
    /**
     * Creates new form espectaculosIngresados
     */
    public espectaculosIngresados() {
        this.ICE = Fabrica.getInstance().getIControladorEspectaculo();
        this.ICP = Fabrica.getInstance().getIControladorPaquete();
        this.ICF = Fabrica.getInstance().getIControladorFuncion();
        initComponents();
        cargarTabla();
    }
    
    public void cargarTabla()
    {
        DefaultTableModel table = new DefaultTableModel();
        ArrayList<Espectaculo> datos;
        String[] filas = new String[5];
        table.addColumn("Nombre");
        table.addColumn("Artista");
        table.addColumn("Plataforma");
        table.addColumn("URL");
        table.addColumn("Costo");
        datos = ICE.obtenerEspectaculos("S");
        for(int i = 0; i<datos.size(); i++)
        {
            filas[0] = datos.get(i).getNombre().toString();
            filas[1] = datos.get(i).getDescripcion().toString();
            filas[2] = datos.get(i).getPLataforma();
            filas[3] = datos.get(i).getURL().toString();
            filas[4] = String.valueOf(datos.get(i).getCosto());
            table.addRow(filas);
        }
        tblEspectaculos.setModel(table);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEspectaculos = new javax.swing.JTable();
        btnRefrescar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Espectaculos ingresados");

        tblEspectaculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblEspectaculos.setToolTipText("");
        tblEspectaculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblEspectaculosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblEspectaculos);

        btnRefrescar.setText("Refrescar");
        btnRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRefrescar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(btnRefrescar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    private void btnRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarActionPerformed
        cargarTabla();
    }//GEN-LAST:event_btnRefrescarActionPerformed

    private void tblEspectaculosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEspectaculosMousePressed
        if(evt.getClickCount() == 2)
        {
            int fila = tblEspectaculos.getSelectedRow();
            String nombre = (String) tblEspectaculos.getValueAt(fila,0);//selecciono de la fila seleccionada la primera
            
            int resultado = JOptionPane.showConfirmDialog(null, "¿Desea aceptar el espectaculo "+nombre+"?","Aceptar o rechazar espectaculo",JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
            
            if(resultado >= 0 && resultado < 2)//Es decir que coloco que si o que cancelo
            {
                String estado = "A";//Aceptado
                if(resultado == 1)//Rechazado
                {
                    estado = "R";
                }
                ICE.actualizarEstadoEspectaculo(nombre,estado);
                if(estado == "A")
                {
                    JOptionPane.showMessageDialog(this, "Aceptado correctamente.");
                }else if(estado == "R"){
                    JOptionPane.showMessageDialog(this, "Rechazado correctamente.");
                }
                
                cargarTabla();
            }
        }   
    }//GEN-LAST:event_tblEspectaculosMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(espectaculosIngresados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(espectaculosIngresados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(espectaculosIngresados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(espectaculosIngresados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new espectaculosIngresados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefrescar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEspectaculos;
    // End of variables declaration//GEN-END:variables
}
